version: "3.8"
services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./docker:/opt/nodejs
        ports:
          - 3000:3000
        tty: true